### ISSUE TITLE
Configuration Export and Time Series

### ISSUE THREAD

**Issue by mabi38** [Oslandia/QGeoloGIS#57]
Hello, good morning.

Unfortunately I have to deal with 2 problems with the QGeologis plugin (1.3.1). 
1.) Export Configuration
I tried exporting the configuration of  a continuous log (which is working well) via 'Plugins --> QGeologis --> Export configuration to ...'. But I received the following error message:

KeyError: 'timeseries' 
Traceback (most recent call last):
  File "C:/Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGeoloGIS-master\qgis_plugin.py", line 214, in on_export_config
    export_config(self.__config, filename)
  File "C:/Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGeoloGIS-master\config.py", line 210, in export_config
    for layer_cfg in config[subkey]:
KeyError: 'timeseries'

I am a bit confused because I didn't do anything in the configuration with times series.

2.) Time Series
I tried creating the plot of a time series but it didn't work. Assuming that I need to configure  the type 'log measures instantaneous' getting a time series plot I defined an event column which contains the day of the measurement as numerical value (1, 2, 3, 4, ....) and a column with the measured values (e.g. 2, 5, 9,..). Obviously these definitions are not correct. I received some error messages but I am not an expert so I didn't really understood what they mean. Maybe an example of a table with a time series in the correct format would help. 

Regards

Martin

**Comment by delhomer** [comment]
Hello @mabi38,

Regarding your first question, I'm wondering if the fix is available on the `master` branch... Maybe @mhugo could bring a confirmation on that point.

Then considering your timeseries issue, you can check on the materials which is available in the [sample](https://github.com/Oslandia/QGeoloGIS/tree/master/sample) folder (I'm still talking about the `master` branch, sorry for that; it sounds like if a new tag could be useful...) : 
- a small example database with very simple timeseries data can be dumped from `qgeologistest.sql`;
- then you can see it in QGIS after running the `generate_config_test.py` script.

Feel free to ask for more precisions if it is unclear!

Raphaël
